apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "yk-dns-manager.fullname" . }}
  labels:
    {{- include "yk-dns-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get", "list", "watch", "update", "patch"]
