apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yk-dns-manager.fullname" . }}-dns-provider
  labels:
    {{- include "yk-dns-manager.labels" . | nindent 4 }}
data:
  dns-provider.yaml: |
    provider: {{ .Values.dnsProvider.provider | quote }}
    upsert: {{ .Values.dnsProvider.upsert }}
    settings:
      {{- range $key, $value := .Values.dnsProvider.settings }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
