apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yk-dns-manager.fullname" . }}-domain-map
  labels:
    {{- include "yk-dns-manager.labels" . | nindent 4 }}
data:
  domain-map.yaml: |
    {{- range $domain, $ip := .Values.domainMap }}
    {{ $domain | quote }}: {{ $ip | quote }}
    {{- end }}
