apiVersion: v1
kind: Service
metadata:
  name: {{ include "yk-dns-manager.fullname" . }}
  labels:
    {{- include "yk-dns-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "yk-dns-manager.selectorLabels" . | nindent 4 }}
