{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yk-dns-manager.fullname" . }}
  labels:
    {{- include "yk-dns-manager.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "yk-dns-manager.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
{{- end }}
